# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.4.0
# docker run --name localpgsql -e POSTGRES_PASSWORD=ssenol -d -p 5432:5432 -v /home/msenol/data:/var/lib/postgresql/data  postgres

apiVersion: apps/v1
kind: Deployment
metadata:
  name: localpostgres-deployment
  labels:
    app: localpostgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localpostgres
  template:
    metadata:
      labels:
        app: localpostgres
    spec:
      containers:
      - name: localpostgres
        image: docker.io/library/postgres:latest
        imagePullPolicy: Never
        args:
        - postgres
        env:
        - name: POSTGRES_PASSWORD
          value: ssenol
        ports:
        - containerPort: 5432
          hostPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: local-data-host-0
      volumes:
      - name: local-data-host-0
        hostPath:
          path: /pgdata/data2
          type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localpoembooks-deployment
  labels:
    app: localpoembooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localpoembooks
  template:
    metadata:
      labels:
        app: localpoembooks
    spec:
      containers:
      - name: localpoembooks
        image: poembooks
        imagePullPolicy: Never
        command:
        - ./poembooks
        env:
        - name: PG_HOST
          value: "localpostgres-service"
        - name: HOST_PORT
          value: "3002"
        - name: HOST_ADDR
          value: "0.0.0.0"
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: localpoembooks-service
  labels:
    app: localpoembooks
spec:
  type: NodePort
  selector:
    app: localpoembooks
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: localpostgres-service
  labels:
    app: localpostgres
spec:
  type: NodePort
  selector:
    app: localpostgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432